# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build-{build}-{branch}'

platform: x64

configuration:
  - Release

build:
  parallel: true

image:
  - Visual Studio 2017

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: ""

matrix:
  fast_finish: true

init:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%
  # Use Appveyor own Boost 1.67.0
  - set BOOST_ROOT=C:/Libraries/boost_1_67_0
  - set BOOST_LIBRARYDIR=%BOOST_ROOT%/lib64-msvc-14.1

before_build:
  - cmake --version

build_script:
  - cmake -H. -Bbuild
          -G"%GENERATOR%"
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          %CMAKEARGS%
  - cmake --build build
          --config %CONFIGURATION%
          -- %BUILDFLAGS%

deploy: off
